import {test} from 'node:test';
import assert from 'node:assert/strict';
import {handleDelivery} from '../worker/delivery.js';
const env={MAPBOX_ACCESS_TOKEN:'mapbox-test-secret',DELIVERY_ORIGIN:'Condomínio RK, Sobradinho - DF',VEHICLE_KM_PER_LITER:'12',FUEL_PRICE:'4.19',DELIVERY_TRIP_MODE:'round-trip'};
const request=(body={cep:'71540035'},headers={})=>new Request('https://example.test/api/delivery',{method:'POST',headers:{'Content-Type':'application/json',...headers},body:JSON.stringify(body)});
function fake({meters=[12000,8400],features=true}={}){const calls=[];const fetcher=async url=>{const u=String(url);calls.push(u);if(u.startsWith('https://viacep.com.br'))return Response.json({cep:'71540-035',uf:'DF',logradouro:'Rua das Flores',bairro:'Águas Claras',localidade:'Brasília'});if(u.startsWith('https://api.mapbox.com/search/geocode/v6/forward'))return Response.json({features:features?[{type:'Feature',geometry:{type:'Point',coordinates:[-47.8,-15.7]},properties:{}}]:[]});if(u.startsWith('https://api.mapbox.com/directions/v5/mapbox/driving/'))return Response.json({code:'Ok',routes:[{distance:meters.shift()}]});throw new Error('unexpected provider')};return {calls,fetcher}}
test('Mapbox flow calculates round-trip without exposing private data',async()=>{const {calls,fetcher}=fake();const res=await handleDelivery(request(),env,fetcher);const body=await res.json();assert.equal(res.status,200);assert.equal(body.status,'estimated');assert.equal(body.distanceKm,12);assert.equal(body.billableDistanceKm,20.4);assert.equal(body.estimatedCents,Math.round(20.4/12*4.19*100));assert.equal(calls.filter(x=>x.includes('/search/geocode/v6/forward')).length,2);assert.equal(calls.filter(x=>x.includes('/directions/v5/mapbox/driving/')).length,2);assert.ok(!JSON.stringify(body).includes('Condomínio'));assert.ok(!JSON.stringify(body).includes('mapbox-test-secret'));});
test('invalid CEP is rejected before providers',async()=>{let calls=0;const res=await handleDelivery(request({cep:'bad'}),env,async()=>{calls++});assert.equal(res.status,400);assert.equal(calls,0);});
test('strict content type, body limit and same origin',async()=>{assert.equal((await handleDelivery(request({}, {'Content-Type':'application/jsonish'}),env)).status,415);assert.equal((await handleDelivery(request({}, {'Content-Length':'4097'}),env)).status,413);assert.equal((await handleDelivery(request({}, {Origin:'https://foreign.test'}),env)).status,403);});
test('rate limit blocks before providers',async()=>{let called=false;const res=await handleDelivery(request(),{...env,DELIVERY_RATE_LIMITER:{limit:async()=>({success:false})}},async()=>{called=true});assert.equal(res.status,429);assert.equal(called,false);});
