import {readSession,saveSession,validPlanner} from '../lib/session.js';
import React,{useState,useEffect} from 'react';
import WA from './WhatsApp.jsx';
import ExpandableSection from './ExpandableSection.jsx';
import {EVENTS,MAX_SWEETS,number} from '../data/commerce.js';
import {planEvent} from '../lib/planning.js';
import {plannerMessage,track} from '../lib/orders.js';
export default function Planner({onConfigure,open,onToggle}){
 const [saved]=useState(()=>readSession('planner',validPlanner,{eventId:EVENTS[0].id,guests:''}));
 const [eventId,setEventId]=useState(saved.eventId),[guests,setGuests]=useState(saved.guests),[result,setResult]=useState(null),[error,setError]=useState('');
 useEffect(()=>{saveSession('planner',{eventId,guests})},[eventId,guests]);
 function calculate(e){e.preventDefault();try{const next=planEvent(eventId,Number(guests));setResult(next);setError('');track('planner_completed',{event_type:next.event,guests:next.guests,cake_kg:next.cakeKg,quantity_min:next.min,quantity_max:next.max})}catch(err){setResult(null);setError(err.message)}}
 function clear(){setResult(null);setError('')}
 return <ExpandableSection id="quanto-pedir" titleId="planner-title" title="Calculadora para seu evento" label="PARA PLANEJAR" className="planner" open={open} onToggle={onToggle}><div><p>Informe o evento e a quantidade de convidados para ter uma referência de bolo e doces.</p></div><div><form onSubmit={calculate} noValidate><div className="planner-fields"><label className="field" htmlFor="event-type">Tipo de evento<select id="event-type" value={eventId} onChange={e=>{setEventId(e.target.value);clear()}}>{EVENTS.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label><label className="field" htmlFor="guests">Quantidade de convidados<input id="guests" type="number" min="1" step="1" inputMode="numeric" value={guests} aria-invalid={!!error} aria-describedby={error?'planner-error':undefined} onChange={e=>{setGuests(e.target.value);clear()}} required/></label></div>{error&&<p id="planner-error" className="form-error" role="alert">{error}</p>}<button className="button" type="submit">Calcular quantidades</button></form>{result&&<div className="planner-result" aria-live="polite"><h3>Sugestão para {result.guests} pessoas</h3><p>Bolo: aproximadamente <strong>{number(result.cakeKg)} kg</strong><br/>Doces: <strong>{result.min===result.max?`${result.min} unidades`:`entre ${result.min} e ${result.max} unidades`}</strong></p><p className="estimate-note">A faixa de doces foi arredondada para lotes de 50 unidades. Bolo: 1 kg a cada 10 pessoas; pedido mínimo de 1,5 kg. Essa é uma estimativa para ajudar no planejamento. A quantidade ideal pode variar conforme o restante do cardápio e o perfil do evento.</p><div className="planner-actions">{[...new Set([result.min,result.max])].filter(q=>q<=MAX_SWEETS).map(q=><button key={q} type="button" className="button" onClick={()=>{track('planner_to_configurator',{event_type:result.event,guests:result.guests,quantity:q});onConfigure(q)}}>Montar pedido com {q} doces</button>)}</div>{result.max>MAX_SWEETS&&<p>Para quantidades acima de 500 doces, consulte a Nanda pelo WhatsApp.</p>}<WA event="whatsapp_planner" className="text-link" cta_location="planejador" quantity={result.max} message={plannerMessage(result)}>Consultar esta estimativa</WA></div>}</div></ExpandableSection>;
}
